name: shop_cake
description: A new Flutter module project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5 #imported on 25th Jun 2022
  #Equatable
  equatable: ^2.0.3 #imported on 25th Jun 2022
  json_annotation: ^4.5.0 #imported on 25th Jun 2022
  json_serializable: ^6.2.0 #imported on 25th Jun 2022
  build_runner: ^2.1.11 #imported on 25th Jun 2022
  easy_localization: ^3.0.1 #imported on 25th Jun 2022
  flutter_svg: ^1.1.1+1 #imported on 25th Jun 2022
  loading_indicator: ^3.1.0 #imported on 25th Jun 2022
  logger: 1.1.0 #imported on 25th Jun 2022
  progress_indicators: ^1.0.0 #imported on 25th Jun 2022
  convex_bottom_bar: ^3.0.0
  firebase_messaging: ^13.0.0
  firebase_core: ^1.24.0
  flutter_local_notifications: ^9.9.0
  carousel_slider: ^4.1.1
  flutter_image_slideshow: ^0.1.4
  fluttertoast: ^8.0.9
  dropdown_button2: ^1.7.2
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  loadmore: ^2.0.1
  flutter_lints: ^2.0.0
  firebase_core_platform_interface: 4.5.1
  firebase_auth: ^3.3.2
  google_sign_in: ^5.1.1

  common:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/ic_logo.jpg"
  min_sdk_android: 22 # android min sdk min:16, default 21


flutter_intl:
  enabled: true
  class_name: Translate
  output_dir: lib/generated
  arb_dir: lib/l10n

flutter:
  uses-material-design: true

  assets:
    - assets/ #imported on 25th Jun 2022
    - assets/icon/ #imported on 25th Jun 2022
    - assets/images/ #imported on 25th Jun 2022


  fonts: #imported on 25th Jun 2022
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
